export enum PERMISSIONS {
  GET_ALL_USERS = 'GET_ALL_USERS',
  GET_ALL_STUDENTS = 'GET_ALL_STUDENTS',
  GET_ALL_ROLES = 'GET_ALL_ROLES',
  GET_ALL_FACULTIES = 'GET_ALL_FACULTIES',
  GET_ALL_SPECIALTIES = 'GET_ALL_SPECIALTIES',
  GET_ALL_SUBJECTS = 'GET_ALL_SUBJECTS',
  GET_ALL_LESSONS = 'GET_ALL_LESSONS',
  GET_ALL_GROUPS = 'GET_ALL_GROUPS',
  GET_ALL_REFRESH_TOKENS = 'GET_ALL_REFRESH_TOKENS',

  GET_OWN_STUDENTS = 'GET_OWN_STUDENTS',
  GET_OWN_FACULTIES = 'GET_OWN_FACULTIES',
  GET_OWN_SPECIALTIES = 'GET_OWN_SPECIALTIES',
  GET_OWN_SUBJECTS = 'GET_OWN_SUBJECTS',
  GET_OWN_GROUPS = 'GET_OWN_GROUPS',
  GET_OWN_LESSONS = 'GET_OWN_LESSONS',

  CREATE_FACULTY = 'CREATE_FACULTY',
}
